name: Deploy OpenTelemetry Demo to Local Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Docker Compose V2
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Start OpenTelemetry Demo with Docker Compose
      run: |
        docker compose up --force-recreate --remove-orphans --detach
