name: Deploy OpenTelemetry Demo to Local Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start OpenTelemetry Demo with Docker Compose
      run: |
        docker compose up --force-recreate --remove-orphans --detach
